{
 "title": "Spring Batch Dashboard with pushgateway",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Job Launch Total Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_batch_job_launch_count_total",
     "legendFormat": "{{spring_batch_job_name}} {{spring_batch_job_status}}"
    }
   ]
  },
  {
   "title": "Job COMPLETED Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_batch_job_active_seconds_count{spring_batch_job_active_status=\"COMPLETED\"}",
     "legendFormat": "{{spring_batch_job_active_name}}"
    }
   ]
  },
  {
   "title": "Job FAILED Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_batch_job_active_seconds_count{spring_batch_job_active_status=\"FAILED\"}",
     "legendFormat": "{{spring_batch_job_active_name}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "spring_batch_job_active_seconds_max",
     "legendFormat": "{{spring_batch_job_active_name}}"
    }
   ]
  },
  {
   "title": "Item Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_batch_item_read_seconds_count[1m])",
     "legendFormat": "{{spring_batch_item_read_step_name}}"
    }
   ]
  },
  {
   "title": "Item Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_batch_chunk_write_seconds_count[1m])",
     "legendFormat": "{{spring_batch_chunk_write_step_name}}"
    }
   ]
  }
 ]
}