{
 "title": "POS (Point Of Sale) System",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Eureka Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"eureka_server_prometheus\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{job=\"eureka_server_prometheus\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\", job=\"eureka_server_prometheus\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\", job=\"eureka_server_prometheus\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"gateway_service_prometheus\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{job=\"gateway_service_prometheus\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\", job=\"gateway_service_prometheus\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\", job=\"gateway_service_prometheus\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "User Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"user_service_prometheus\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{job=\"user_service_prometheus\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\", job=\"user_service_prometheus\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\", job=\"user_service_prometheus\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Requests Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(method, uri)(rate(http_server_requests_seconds_count{job=\"user_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"}[1m]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Requests Average Duration",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(method, uri)(http_server_requests_seconds_sum{job=\"user_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"}) / sum by(method, uri)(http_server_requests_seconds_count{job=\"user_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Store Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"store_service_prometheus\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{job=\"store_service_prometheus\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\", job=\"store_service_prometheus\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\", job=\"store_service_prometheus\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Requests Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(method, uri)(rate(http_server_requests_seconds_count{job=\"store_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"}[1m]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Requests Average Duration",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(method, uri)(http_server_requests_seconds_sum{job=\"store_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"}) / sum by(method, uri)(http_server_requests_seconds_count{job=\"store_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Trade Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"trade_service_prometheus\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{job=\"trade_service_prometheus\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\", job=\"trade_service_prometheus\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\", job=\"trade_service_prometheus\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Requests Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(method, uri)(rate(http_server_requests_seconds_count{job=\"trade_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"}[1m]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Requests Average Duration",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(method, uri)(http_server_requests_seconds_sum{job=\"trade_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"}) / sum by(method, uri)(http_server_requests_seconds_count{job=\"trade_service_prometheus\", uri!=\"/**\", uri!=\"/actuator\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  { "title": "Batch Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"batch_server_prometheus\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{job=\"batch_server_prometheus\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\", job=\"batch_server_prometheus\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\", job=\"batch_server_prometheus\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "spring_batch_job_seconds_max",
     "legendFormat": "{{spring_batch_job_name}} {{spring_batch_job_status}}"
    }
   ]
  },
  {
   "title": "Job Execution Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(spring_batch_job_seconds_count[1m]) * 60",
     "legendFormat": "{{spring_batch_job_name}} {{spring_batch_job_status}}"
    }
   ]
  },
  {
   "title": "Job Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(spring_batch_job_seconds_count{spring_batch_job_status=\"FAILED\"}[5m])) by (spring_batch_job_name, spring_batch_job_status)) / (sum(rate(spring_batch_job_seconds_count[5m])) by (spring_batch_job_name, spring_batch_job_status))",
     "legendFormat": "{{spring_batch_job_name}} {{spring_batch_job_status}}"
    }
   ]
  },
  {
   "title": "Item Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_batch_item_read_seconds_count[1m])",
     "legendFormat": "{{spring_batch_item_read_step_name}}"
    }
   ]
  },
  {
   "title": "Item Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_batch_chunk_write_seconds_count[1m])",
     "legendFormat": "{{spring_batch_chunk_write_step_name}}"
    }
   ]
  }
 ]
}