spring:
  config:
    activate:
      on-profile: prod
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    service:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    meta:
      jdbc-url: ${SPRING_META_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

server:
  port:
    ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: prometheus