spring:
  config:
    activate:
      on-profile: prod
  application:
    name: ${SPRING_APPLICATION_NAME}

server:
  port: ${SERVER_PORT}

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}